-- 创建数据库
CREATE DATABASE IF NOT EXISTS jike;
USE jike;

-- 用户表
CREATE TABLE vip (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

-- 文章表
CREATE TABLE articles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  author VARCHAR(100),
  publish_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  tech_stack VARCHAR(100),
  views INT DEFAULT 0
);

-- 用户文章表
CREATE TABLE my_articles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  tech_stack VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  images JSON,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 上传进度表
CREATE TABLE upload_progress (
  id INT AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  uploadedChunks INT DEFAULT 0
);
